### ISSUE TITLE
Does not build if quic or websocket features are disabled

### ISSUE THREAD

**Issue by yu-re-ka** [moparisthebest/xmpp-proxy#3]

**Comment by moparisthebest** [comment]
Yes I utterly broke all that adding in the host-meta support, I plan to redesign the features soon, I don't like that "quic" brings in incoming and outgoing quic, and that there's no way to enable only c2s or s2s for example.

Any suggestions appreciated.

**Comment by moparisthebest** [comment]
This should be fixed now, thanks for being patient :)
